# Generated by Django 4.1.3 on 2022-12-19 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='section',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
