# Generated by Django 4.1.3 on 2022-12-20 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='profil_photo',
            new_name='profile_photo',
        ),
    ]
