# Generated by Django 4.1.3 on 2022-12-21 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_cart_customer'),
        ('store', '0009_remove_cart_product_wish_list'),
    ]

    operations = [
    ]
