# Generated by Django 4.1.3 on 2022-12-21 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_cart_model_delete_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart_Model',
            new_name='Cart',
        ),
    ]
