# Generated by Django 4.1.3 on 2022-12-22 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_branch_delete_musteri'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.branch'),
            preserve_default=False,
        ),
    ]
