# Generated by Django 4.1.3 on 2022-12-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_customer_branch_product_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
