# Generated by Django 4.1.3 on 2022-12-19 03:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_section_delete_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_size',
            old_name='beden',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='product',
            name='information',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
