# Generated by Django 4.1.3 on 2022-12-19 04:54

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_beden_product_size_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.get_file_path),
        ),
    ]
