# Generated by Django 4.1.3 on 2022-12-21 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_cart_item_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart_Item',
        ),
    ]
