# Generated by Django 4.1.3 on 2022-12-21 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0015_delete_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish_list',
            name='customer',
        ),
        migrations.AddField(
            model_name='wish_list',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
