# Generated by Django 4.1.3 on 2022-12-21 23:41

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_product_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_review',
            name='review_photo',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.get_file_path),
        ),
    ]
