# Generated by Django 4.1.3 on 2022-12-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_product_review_review_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=20)),
                ('post_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name='Musteri',
        ),
    ]
